In [ ]:
df1=pd.read_csv("adult.csv")
df1.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [ ]:
df1.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [ ]:
for x in ["workclass", "education", "marital-status", "occupation", "relationship", "race", "gender", "native-country", "income"] :
  print(x)
  print(df1[x].value_counts())

workclass
workclass
Private             33906
Self-emp-not-inc     3862
Local-gov            3136
?                    2799
State-gov            1981
Self-emp-inc         1695
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64
education
education
HS-grad         15784
Some-college    10878
Bachelors        8025
Masters          2657
Assoc-voc        2061
11th             1812
Assoc-acdm       1601
10th             1389
7th-8th           955
Prof-school       834
9th               756
12th              657
Doctorate         594
5th-6th           509
1st-4th           247
Preschool          83
Name: count, dtype: int64
marital-status
marital-status
Married-civ-spouse       22379
Never-married            16117
Divorced                  6633
Separated                 1530
Widowed                   1518
Married-spouse-absent      628
Married-AF-spouse           37
Name: count, dtype: int64
occupation
occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
?                    2809
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64
relationship
relationship
Husband           19716
Not-in-family     12583
Own-child          7581
Unmarried          5125
Wife               2331
Other-relative     1506
Name: count, dtype: int64
race
race
White                 41762
Black                  4685
Asian-Pac-Islander     1519
Amer-Indian-Eskimo      470
Other                   406
Name: count, dtype: int64
gender
gender
Male      32650
Female    16192
Name: count, dtype: int64
native-country
native-country
United-States                 43832
Mexico                          951
?                               857
Philippines                     295
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Guatemala                        88
Poland                           87
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Nicaragua                        49
Greece                           49
Peru                             46
Ecuador                          45
France                           38
Ireland                          37
Thailand                         30
Hong                             30
Cambodia                         28
Trinadad&Tobago                  27
Laos                             23
Outlying-US(Guam-USVI-etc)       23
Yugoslavia                       23
Scotland                         21
Honduras                         20
Hungary                          19
Holand-Netherlands                1
Name: count, dtype: int64
income
income
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [ ]:
df1.replace("?", np.nan, inplace=True)

In [ ]:
miss_col=df1.isnull().sum()
print(miss_col[miss_col>0])

workclass         2799
occupation        2809
native-country     857
dtype: int64

In [ ]:
for x in ["workclass", "occupation", "native-country"] :
  df1[x]=df1[x].fillna(df1[x].mode()[0])

(48842, 15)
(48842, 15)
(48842, 15)

In [ ]:
miss_col=df1.isnull().sum()
print(miss_col[miss_col>0])

Series([], dtype: int64)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for x in ["workclass", "education", "marital-status", "occupation", "relationship", "race", "gender", "native-country", "income"] :
  df1[x]=le.fit_transform(df1[x])
  print(df1[x])

0        3
1        3
2        1
3        3
4        3
        ..
48837    3
48838    3
48839    3
48840    3
48841    4
Name: workclass, Length: 48842, dtype: int64
0         1
1        11
2         7
3        15
4        15
         ..
48837     7
48838    11
48839    11
48840    11
48841    11
Name: education, Length: 48842, dtype: int64
0        4
1        2
2        2
3        2
4        4
        ..
48837    2
48838    2
48839    6
48840    4
48841    2
Name: marital-status, Length: 48842, dtype: int64
0         6
1         4
2        10
3         6
4         9
         ..
48837    12
48838     6
48839     0
48840     0
48841     3
Name: occupation, Length: 48842, dtype: int64
0        3
1        0
2        0
3        0
4        3
        ..
48837    5
48838    0
48839    4
48840    3
48841    5
Name: relationship, Length: 48842, dtype: int64
0        2
1        4
2        4
3        2
4        4
        ..
48837    4
48838    4
48839    4
48840    4
48841    4
Name: race, Length: 48842, dtype: int64
0        1
1        1
2        1
3        1
4        0
        ..
48837    0
48838    1
48839    0
48840    1
48841    0
Name: gender, Length: 48842, dtype: int64
0        38
1        38
2        38
3        38
4        38
         ..
48837    38
48838    38
48839    38
48840    38
48841    38
Name: native-country, Length: 48842, dtype: int64
0        0
1        0
2        1
3        1
4        0
        ..
48837    0
48838    1
48839    0
48840    0
48841    1
Name: income, Length: 48842, dtype: int64

In [ ]:
for x in ["age", "fnlwgt", "educational-num", "capital-gain", "capital-loss", "hours-per-week"] :
  Q1=df1[x].quantile(0.25)
  Q3=df1[x].quantile(0.75)

  IQR=Q3-Q1

  lowerbound=Q1- 1.5*IQR
  upperbound=Q3+ 1.5*IQR

  df1=df1[(df1[x] >= lowerbound) & (df1[x] <= upperbound)]

  print(df1.shape)

(17792, 15)
(17792, 15)
(17792, 15)
(17792, 15)
(17792, 15)
(17792, 15)